-- creation new table

-- Memory type table

CREATE TABLE MemoryType(
  ID int not NULL AUTO_INCREMENT PRIMARY KEY,
  MemoryType NVARCHAR(50)
);

INSERT INTO MemoryType(MemoryType) VALUES ('EPC');
INSERT INTO MemoryType(MemoryType) VALUES ('TID');
INSERT INTO MemoryType(MemoryType) VALUES ('USER');

-- All available tag 

CREATE TABLE TAGCodeRFID(
  ID int not NULL AUTO_INCREMENT PRIMARY KEY,
  MemoryTypeID int NOT NULL,
  MemoryCode NVARCHAR(50)
);

INSERT INTO TAGCodeRFID(MemoryTypeID, MemoryCode) VALUES (1, 'FFEEDDCCBBAA009988776655');
INSERT INTO TAGCodeRFID(MemoryTypeID, MemoryCode) VALUES (1, '00998877665544332211AABB');
INSERT INTO TAGCodeRFID(MemoryTypeID, MemoryCode) VALUES (2, '11223344556677889900FFDD');
INSERT INTO TAGCodeRFID(MemoryTypeID, MemoryCode) VALUES (2, 'AAFFBBDDCCEE009911882277');
INSERT INTO TAGCodeRFID(MemoryTypeID, MemoryCode) VALUES (3, 'FFAADDBBEECC990088117722');
INSERT INTO TAGCodeRFID(MemoryTypeID, MemoryCode) VALUES (3, 'BBAA99887766554433221100');

-- All constraint

ALTER TABLE MEMORYTYPE ADD UNIQUE (ID);

ALTER TABLE TAGCodeRFID ADD FOREIGN KEY (MemoryTypeID) REFERENCES MemoryType(ID);

ALTER TABLE TAGCODERFID ADD UNIQUE (MemoryCode);